Added in release label script

diff --git a/.github/workflows/run-pr-tag-gen.yml b/.github/workflows/run-pr-tag-gen.yml
--- a/.github/workflows/run-pr-tag-gen.yml
+++ b/.github/workflows/run-pr-tag-gen.yml
@@ -52,6 +52,24 @@ jobs:
           fi
 
           echo "tag=${latest_tag}" >> $GITHUB_OUTPUT
+      - name: Get release-label from pull request
+        id: release-label
+        run: |
+          label=$(jq -r ".pull_request.labels[].name | select(test(\"release/(major|minor|patch)\"))" "${GITHUB_EVENT_PATH}")
+
+          if [ -z "${label}" ]; then
+              echo "::debug:: no release label"
+              exit 0
+          fi
+
+          if [ "$(echo "${label}" | wc -l)" -ne 1 ]; then
+              echo "::error:: multiple release labels not allowed: labels=$(echo "${label}" | tr '\n' ' ')"
+              exit 1
+          fi
+
+          level=${label#"release/"} # e.g.) 'release/major' => 'major'
+
+          echo "level=${level}" >> $GITHUB_OUTPUT
 
       - name: set bump level
         id: set-bump-level
